commons:
  sitename: Kiribi Ususama
  description: gulpを使用した小・中規模Webサイト制作用のボイラープレート
  year: 2019
  author: アルム＝バンド
  url: http://localhost:3000/
  ogpimage: img/eyecatch.jpg
  twitteraccount: Bredtn_1et
param:
  news:
    indexcount: 3
    newscount: 6
  ogp:
    ogpimage: img/eyecatch.jpg
    twitteraccount: Bredtn_1et
    newsthumbnail: img/thumbnails/
  analytics: UA-132392783-6
  searchconsole: yqQ6v922sd1miKGt5_5cm1Z8MTzmNyyuM4v8_dn0qLw
  articlesns:
    twitter: true
    facebook: true
    hatena: true
    line: true
    pocket: true
    feedly: true
