usephp: false
news: true
ssl: true
styleguide: true
sitemap: true
sitemap_xml: true
rss: true
ogp: true
analytics: true
searchconsole: true
pagetop: true
articlesns: true
themecolor: true
safari: true
chrome: true
fixedanchor_scss: true
fixedanchor_js: true
lightbox: true
slick: false
svghexagon: false
imagemin: true
sitesearch: true
wordpress: false
advanced_typo: true
noscript: true